
dist: bionic

language: cpp

compiler:
  - clang
  - gcc
  
install:
  - sudo apt-get install libboost-dev

script:
- cmake --version
- mkdir build && cd build
- cmake -DCMAKE_CXX_COMPILER=$COMPILER -DCMAKE_BUILD_TYPE=RELEASE ..
- make
- ./test-dtr
